### ISSUE TITLE
White border on Dark Terminal edge

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#119]
There is an odd White border on Gnome-Terminal's dark theme, one which does not appear on any other dark themed apps.

![terminal border](https://i.imgur.com/tDxOkbG.png)

**Comment by godlyranchdressing** [comment]
You're using the dark terminal theme while using the light theme? Maybe try refreshing the Shell? 

That line is a box shadow that's supposed to be the same shade as the headerbar. It's there to even out the (unavoidable) black aliasing behind a couple windows' rounded corners.

If the terminal is pulling colors from the dark gtk file then it should be using the correct, dark headerbar color. Unless it's pulling it from the light gtk file, but those dark colors aren't defined anywhere in it. 

I'll see if I can make the aliasing solution more foolproof to avoid issues like this since this could show up in other programs.

**Comment by ElectricGestalt** [comment]
Oh you're right. I don't normally need to refresh the shell when I update your theme so I thought it was a bug. I'll be sure to do so next time.
