### ISSUE TITLE
Shutdown menu's volume control

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#123]
Shutdown menu's volume control seems little weird when you have maximized volume and it looks like it's closer to 95%.
![image](https://user-images.githubusercontent.com/26358664/27290666-9b206a30-5516-11e7-9b6b-b52c2335ba1e.png)

**Comment by amrsaraya** [comment]
i think he did that on purpose, and in my opinion it looks better this way.

**Comment by juhaku** [comment]
Actually it just was in my old theme, now it looks as it should. when the volume is maximized it shows as maximized. 
I think it looks better with the real progress. Oterwise it looks broken like would be missing a pull. 

Afterall no issues. false alarm.

**Comment by godlyranchdressing** [comment]
I'm actually noticing it on my end as well. I never thought anything of it since I don't usually have my volume on the maximum setting. I think the Shell might be assuming that the slider ball (which is invisible in the theme) would cover up that blank space. I don't really want to put back the slider so I'll see if I can get around it somehow.

**Comment by godlyranchdressing** [comment]
Fixed.
