### ISSUE TITLE
Debian varient

### ISSUE THREAD

**Issue by danPixl** [godlyranchdressing/United-GNOME#140]
Ubuntu shouldn't leave it's father out in the cold when it comes to style.

**Comment by godlyranchdressing** [comment]
That's actually semi-done already. You can download it right now from off the repo:
[United-Debian](https://github.com/godlyranchdressing/United-GNOME/blob/master/United-Debian.tar.gz)
[United-Debian-Compact](https://github.com/godlyranchdressing/United-GNOME/blob/master/United-Debian-Compact.tar.gz)

Whenever I work on the theme I just push compiled versions directly to the repo and some awesome people point out any bugs/ugly things to me until I make a release that would show up in other places. The archives on the repo are never super buggy so that's perfectly usable if you want to give it a go.
