### ISSUE TITLE
New padding

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#141]
I notice the padding on context menus was changed. Were people unhappy with them being thicker? I liked them that way but I understand if others didn't.

**Comment by godlyranchdressing** [comment]
I've added a little more padding. And not really, with a compact variant making things "too big" isn't really _that_ important anymore, but the size of context menu items still really stuck out so I just gave it the "normal size" variable instead of keeping the old value. Let me know if the new size is okay or not.

**Comment by ElectricGestalt** [comment]
Oh wow, yeah that's perfect thanks!
