### ISSUE TITLE
Gnome Shell accent colors should follow the distro color hint

### ISSUE THREAD

**Issue by colemickens** [godlyranchdressing/United-GNOME#151]
It would be great if the OS-specific themes also used their OS highlight color instead of everything using the Ubuntu orange. (Sliders in the global menu, etc)

**Comment by godlyranchdressing** [comment]
Sorry, I'm kind of slow sometimes. What distro color hint? Are you suggesting the accent color (purple in Ubuntu's case) be used more instead of the primary color or are there some variants that use Ubuntu's orange instead of their own primary color?

**Comment by colemickens** [comment]
The Arch one seems to use the Ubuntu orange accent everywhere instead of a more appropriate blue/light-blue.

**Comment by godlyranchdressing** [comment]
Ohh. That's not supposed to be happening, but I'm not getting that issue with the current versions on the repo or gnome-look. Is the launcher icon the Arch logo? Are you using one of the login themes?

**Comment by colemickens** [comment]
I'm not using a login theme as far as I know (it's just standard GDM).

The launcher icon is indeed correctly the Arch logo.

**Comment by godlyranchdressing** [comment]
What version of GNOME are you using? Is the GTK theme fine? I'm not sure what else to check, I hate to utter the usual "works on my machine" but it looks fine on my end. 

![fasd](https://user-images.githubusercontent.com/27529229/29370422-bd6e9554-8251-11e7-87a7-62ebb60556e0.png)

Maybe try redownloading it? If it's the global menu that uses Ubuntu's orange, it could be that the extension has hardcoded colors.

**Comment by colemickens** [comment]
I wonder if my Arch package is old. That panel is not transparent for me. The colors on it match yours though. On the user drop down, the volume and brightness sliders are orange, rather than blue.

**Comment by colemickens** [comment]
Did you possibly fix this since the 2.2 release? That's what the Arch package is installing. (from the 2.2 tag in git)

**Comment by colemickens** [comment]
![screenshot from 2017-08-19 15-53-37](https://user-images.githubusercontent.com/327028/29490621-cdee3220-84f6-11e7-931c-e49afc301e25.png)

**Comment by ceyhunnabiyev** [comment]
@godlyranchdressing , I think all controls (bars, checkboxes, buttons, radiobuttons and etc.) should be in distribution specific color. Think about that please,  for example, I selected United-Arch, but there are  orange (for example, gnome mpv, gnome sushi time duration bar), green, and blue control colors (Arch Color).  Does that looks cool? I think no.

**Comment by godlyranchdressing** [comment]
Wow. I'm sorry, I was misunderstanding the whole time. That's the accent color (that isn't set in stone for the Arch variant). Ubuntu, Fedora and I think OpenSUSE's variants all use colors based on their official design guidelines while the other variants don't. So I'm open to changing Arch's accent color (especially since Fedora uses a similar gold), but I'm not going to get rid of it completely. I'll leave something like that for a fork, along with what @ceyhunnabiyev is requesting.

While it isn't a 1:1 copy, I do try to follow the [Suru guidelines](http://design.ubuntu.com/apps/get-started/design-philosophy).

**Comment by colemickens** [comment]
So you'd be in support of a PR that replaces the orange accents with the Arch blue accent in just the Arch variant? Just want to make sure I understand since you closed this out (I guess since the other variants already follow their distro's scheme?)

**Comment by godlyranchdressing** [comment]
I was thinking something more like Flat-Plat-Blue, which is a fork of Flat-Plat with blue as the primary color. I'll just go ahead and do it as United-Monochrome or something. I'll make sure to link to it here.

In Arch's case, I just chose that yellow (#FF9010, not Ubuntu's #E95420) since it fit with the blue. It's not really official or semi-official like Ubuntu's purple that's used for its accent color, so if someone suggested a replacement color that was more appropriate, I'll replace it.

**Comment by godlyranchdressing** [comment]
https://github.com/godlyranchdressing/United-Monochrome

**Comment by colemickens** [comment]
I see, I didn't understand until now that you'd intentionally chosen accent colors. Thanks so much for creating the fork (although I can't help but feel like that's going to be a maintenance burden, versus something that would be configurable via autoconf/etc)!

**Comment by godlyranchdressing** [comment]
@colemickens No problem and yep, I'll have to get to learning that at some point.
