### ISSUE TITLE
Applications icon isn't full width

### ISSUE THREAD

**Issue by yotamN** [godlyranchdressing/United-GNOME#161]
The ubuntu icon in Dash to Dock is not full width. I noticed that after using the login gnome shell script by I'm not sure it caused it, maybe I just didn't noticed before. Here is a screenshot:

![screenshot from 2017-10-16 18-21-03](https://user-images.githubusercontent.com/5249239/31620122-1685883c-b29f-11e7-8035-dac64b8a83fd.png)

**Comment by juhaku** [comment]
This comes little late.. but before you run the install script you should edit the gnome-shell.css file followingly: [https://github.com/godlyranchdressing/United-GNOME/blob/master/extras/login-gnome-shell/must_fix_css_for_login.txt](https://github.com/godlyranchdressing/United-GNOME/blob/master/extras/login-gnome-shell/must_fix_css_for_login.txt)

There are some fixes that need to be taken account since they are not available in the theme itself. One of them is the padding for the icon.
