### ISSUE TITLE
Control window drop shadows

### ISSUE THREAD

**Issue by alpha0010** [godlyranchdressing/United-GNOME#172]
Question: If I want to tweak this theme locally, what do I edit to change the size of the drop shadows around each window?

**Comment by godlyranchdressing** [comment]
That'll be the box-shadow property under "decoration". It should be around line 5408 (it is on the Arch variant).

`box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.05), 0 0 4px 4px rgba(0, 0, 0, 0.05), 0 0 6px 6px rgba(0, 0, 0, 0.05), 0 0 8px 8px rgba(0, 0, 0, 0.05);`

If you're editing the values you'll need to make sure that you also do the same thing to "decoration:backdrop", ".fullscreen decoration" and ".fullscreen decoration:backdrop" otherwise the windows will jump around.

**Comment by alpha0010** [comment]
Thank you, works great.

**Comment by alpha0010** [comment]
Hmm... *almost* great.  It seems gnome terminal is unaffected; any idea why?  (I am using Ubuntu 17.10, if that is relevant.)

**Comment by godlyranchdressing** [comment]
You need to get it to "refresh" and start using the modified theme. Nautilus has the same issue sometimes since they're both ongoing services so unless you switch to a different theme and back again, force kill the process or refresh GNOME they might still be using the old CSS rules. So for the terminal you'll need to do one of these: 

`Alt + F2` and type in `r` 
Run `killall gnome-terminal-server` in a terminal

**Comment by alpha0010** [comment]
Neither of those two commands nor rebooting the machine caused an update.

**Comment by alpha0010** [comment]
In any case, thanks.  I will just keep tinkering, see what I can find out.
