### ISSUE TITLE
Purple Selection Boxes

### ISSUE THREAD

**Issue by PlwjrtheSecond** [godlyranchdressing/United-GNOME#34]
On some programs the selection boxes are purple with white or black text.
![designproblem](https://cloud.githubusercontent.com/assets/24211342/25787573/ae97447a-3370-11e7-82b7-008a792c1802.png)
I don't know if this is intentional.

**Comment by godlyranchdressing** [comment]
It isn't. Though I managed to clean up all these mishaps, the more-common purple has regrettable been scrapped in V2 because of a Firefox issue so all the black on purple problems should be gone. A kinda-beta release archive is in the V2 branch for now. There are a couple small issues I've spotted but you're free to try it.

**Comment by PlwjrtheSecond** [comment]
Just tested it, works really well! The purple selection boxes are gone!
