### ISSUE TITLE
Orange overhang over application button?

### ISSUE THREAD

**Issue by BooBerry** [godlyranchdressing/United-GNOME#36]
I'm not sure if this is intended or some sort of bug. Anyways, I'm using the latest build linked on gnome-look.org and the latest Dash to Dock (with the icon limit set to a size of 42 px) and I'm seeing this when I click the Application Button;

![bugged button](https://cloud.githubusercontent.com/assets/5448916/25807994/4d352fa4-33ce-11e7-850d-29ed3ce76854.png)

Is the top orange part of the button supposed to overhang a few pixels like that when pressing the button? It doesn't do it in my virtual machine, but does it on my main install. I'm using a 2560x1440 resolution monitor with the latest Nvidia proprietary drivers.

**EDIT:** Happens in the latest Ubuntu V2.0 too.

**Comment by godlyranchdressing** [comment]
Gloriously sized monitor. That's supposed to be like that. I know it's not ideal, if you have your dock 48px wide then it _should_ look seamless but I can't just assume everyone's going to have the same monitor and setup as I do. I'll just make the activities button become the primary color (orange in the ubuntu variant's case) without the box shadow for now since it's the safest thing to do for now.

![icons](https://cloud.githubusercontent.com/assets/27529229/25810730/ff98e784-33de-11e7-9fbe-11a6c682c39d.jpg)

**Comment by BooBerry** [comment]
Yep, at 48px with shrink the dash disabled, it looks fine again.

Even with a 1440p monitor, I don't really like the 48px icons (same with vanilla Ubuntu).

**Comment by BooBerry** [comment]
Fixed in the latest version.
