### ISSUE TITLE
Regression in Nautilus popover

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#50]
The symbol for either the list or folder view should be white when active but is now orange like the background.

![Nautilus popover](http://u.cubeupload.com/cynicist/nautiluspopover.png)

**Comment by godlyranchdressing** [comment]
Damn. That popover menu doesn't seem to be in 3.22.

**Comment by ElectricGestalt** [comment]
Didn't work for me.

**Comment by godlyranchdressing** [comment]
Oh no. Guess I'll upgrade through Copr.

**Comment by ElectricGestalt** [comment]
Wow I found it. What a pain lol.

button.image-button:not(.text-button):active image,
button.image-button:not(.text-button):checked image {
  color: white;
}

It's currently set to orange, but it should look like the above.

**Comment by godlyranchdressing** [comment]
Yep. And then you'll notice that fixing that one thing broke something else. 

:active is the state for an element currently being clicked/interacted with so that's why it turned white on click. I settled on just slightly darkening the primary color for the active state in the last change I pushed.

I upgraded to 3.24 but I still don't see that popover menu. Maybe it's an Ubuntu change. Either way, I just made and pushed the same change you made but limited it to the popover menu in case it messes something else up.
