### ISSUE TITLE
Highlighted Checkboxes

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#7]
Selecting any item with a filled in checkbox causes the checkbox to become invisible, when it should be a White check inside of a White box. You can observe this behavior in the Preferences of Nautilus under the List Columns tab.

**Comment by godlyranchdressing** [comment]
Just wanted to say I'm working on this, though so far even a specificity bump hasn't worked in forcing selected checkboxes to be white.

**Comment by ElectricGestalt** [comment]
Not sure if this makes any difference, but is the check mark White, or transparent? I notice that when I hover over one of these areas (where you can change the order of options), triggering a switch from the White bg to a Gray one, the check mark also changes to the color Gray.

**Comment by godlyranchdressing** [comment]
I just checked (heh) it, it's indeed transparent. I forgot why I wanted to move over to Arc's assets till now. A couple of Flat-Plat's assets appear to be pngs and not actual objects or _something_, since I'm not entirely sure why I can't edit them. I'll have to look into getting new assets. Either some of Unity 8's if I can, or Arc's.

**Comment by godlyranchdressing** [comment]
In-progress.
