### ISSUE TITLE
Rounded window corners seem impossible

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#71]
@godlyranchdressing, new TODO.md update said "GTK2 apps only have their headerbars curved".
Does that mean GTK3 apps' headerbar will be straight corners like old releases ?

**Comment by godlyranchdressing** [comment]
No, it's just something I need to fix. I'm starting to think that I can't though. While it looks awesome when it works, there's too many programs where it doesn't. 

There's the black background which I'm noticing doesn't seem isolated to GTK2 programs and then there's a couple programs like GNOME Maps and Nautilus where their widgets draw over the bottom corners so the corners aren't visible. 

The compromise might just be making the headerbar rounding a bit more extreme (just 10px instead of 6px) and dumping the rounded bottom corners. Maybe GTK4 will save us. Something like pic related is an option for a little extra flair though I get the feeling it might be a _bit_ divisive to most people.

![1](https://cloud.githubusercontent.com/assets/27529229/26280638/8f54369a-3d89-11e7-843e-b65d4ac41b59.jpg)
https://a.pomf.cat/thtsbw.webm

**Comment by amrsaraya** [comment]
I like the idea of making headerbar rounding more extreme, i think it will be awesome. But, i don't like the shape of rounding shadow around window.

Straight bottom corners and rounded headerbar make window looks more beautiful and more realistic.

**Comment by godlyranchdressing** [comment]
Made the changes and pushed.

**Comment by amrsaraya** [comment]
woow!! .. it looks awesome, i didn't think it will be that much beauty.
Good job!
