### ISSUE TITLE
First tab's text is bold by default

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#86]
first tab's text is bold when inactive, and when focus on first tab and refocus to another one .. the tab back to normal font again.
![screenshot from 2017-05-24 01-12-01](https://cloud.githubusercontent.com/assets/21042432/26380357/d48146fa-4026-11e7-91db-eb9b7bf91cb4.png)

**Comment by godlyranchdressing** [comment]
Seems to work fine on my end. What distro and Gnome version are you running?

**Comment by amrsaraya** [comment]
I'm using fedora 25 with GNOME 3.22.2

**Comment by godlyranchdressing** [comment]
Double-checked some stuff in the CSS and tried other apps with the same widget but I'm still not running into it. Is it just System Monitor acting like that or does GNOME Music/Software/Calendar act like that too?

**Comment by amrsaraya** [comment]
System Monitor and Calendar too.
Software is fine.
so i don't know what causes this problem.

**Comment by godlyranchdressing** [comment]
I forgot I was running 3.24 on Fedora. I downgraded to 3.22 and I'm noticing it as well. It looks like it only affects System Monitor.  The only thing different about System Monitor's tabs is that it reopens on the last tab you had open instead of the first and default "Processes" tab so I'm guessing the bold text problem stems from something related to that. I can't override the bold style, either.

![a](https://cloud.githubusercontent.com/assets/27529229/26386056/67abb2a8-3ff0-11e7-96e9-b8c948cf4254.jpg)

It doesn't happen in 3.24 so I'm closing this as a GNOME bug.

**Comment by amrsaraya** [comment]
Aha, thanks for information .
