### ISSUE TITLE
Buttons all white when not focused.

### ISSUE THREAD

**Issue by VandaLHJ** [godlyranchdressing/United-GNOME#96]
It's easy to check. Install geary and open any email with images, you have two choices, to show images or not - they are all white.

Another is selecting text in browser with lmb and clicking elsewhere, text turn all white.
![zrzut ekranu z 2017-05-27 11-27-56](https://cloud.githubusercontent.com/assets/28790923/26520279/958d43d0-42cf-11e7-8500-a1f8a69283a5.png)

![zrzutgit](https://cloud.githubusercontent.com/assets/28790923/26522454/4fa64fb0-4301-11e7-8a59-e5cd22d44713.png)

**Comment by godlyranchdressing** [comment]
Is that selection problem only in Opera?

And I'll check out Geary, I haven't tested it since it very annoyingly doesn't support sign-ins with 2FA turned on.

**Comment by VandaLHJ** [comment]
No, chrome is also affected, especially when we talk about disquss. It's not exactly white then, but very light grey on white. In geary it's totally white on white.

**Comment by VandaLHJ** [comment]
Oh, and both of those show another bug, with Pixel Saver top right buttons are not inherited (X _ Square - quit min max).

**Comment by godlyranchdressing** [comment]
I checked out Geary and the issue seems to come from those buttons (show images/show from sender) always being in the active state. They're using the white text color that a button has when it's clicked on. 

The buttons might just need to be reworked to mimic Suru's which would be more foolproof in avoiding these visibility problems. There's Firefox, now Geary and a couple GTK2 apps (which already have a different button style to avoid similar issues and that bugs me just a little) 

![button](https://cloud.githubusercontent.com/assets/27529229/26523326/57223100-42e3-11e7-861b-4f778186658d.png)

**Comment by VandaLHJ** [comment]
What about using official color palette ? http://design.ubuntu.com/brand/colour-palette
Warm Grey looks fitting for buttons.
100%#AEA79F
90%#B6AFA8
80%#BEB8B2
70%#C6C1BB
60%#CECAC5
50%#D6D3CF
45%#DAD7D3
40%#DEDBD8
35%#E2E0DD
30%#E6E4E2
25%#EAE9E7
20%#EEEDEB
15%#F2F1F0
10%#F6F6F5

**Comment by godlyranchdressing** [comment]
If I go with warm grey I'll need to alter the background color for contrast reasons. Even if I go with Ubuntu's #F5F5F5 I may need to do that. Oh boy.

I'll try and see if I can avoid any sweeping changes since a couple themes do have white text in their button's active state and Geary looks fine.

**Comment by godlyranchdressing** [comment]
Fixed.
