### ISSUE TITLE
Visual-Studio-Code menu hover issue

### ISSUE THREAD

**Issue by ceyhunnabiyev** [godlyranchdressing/United-GNOME#97]
Text  become  unvisible when  I  hover over  any menu item in Visual Studio Code. In an another gtk theme,  this issue doesn't occur.
Regards.

**Comment by godlyranchdressing** [comment]
This is Visual Studio Code that's run through typing "code" into the CLI, right? I haven't actually used VSC before and I know there's some other Visual something by MS so I just want to make sure I'm not mistaking the two (since I'm not seeing the problem you're describing). Either way, I did end up making some changes that might have solved the issue so let me know if it's working properly now when you get the chance. The archives in the repo have been updated so you can try those out.

**Comment by ceyhunnabiyev** [comment]
Yes, "code" from CLI.. I gave you screenshots:

United-Manjaro-Dark
![screenshot from 2017-06-02 01-31-29](https://cloud.githubusercontent.com/assets/5506156/26701739/4f28b48e-4733-11e7-8f9c-9258901182c0.png)

United-Manjaro-Darker
![screenshot from 2017-06-02 01-30-44](https://cloud.githubusercontent.com/assets/5506156/26701773/663b7ea4-4733-11e7-8742-5147d29d5d60.png)

**Comment by godlyranchdressing** [comment]
I don't get that issue but it's possible I fixed it while fixing something else without realizing it. I made a new release. It should be fixed.

**Comment by ceyhunnabiyev** [comment]
@godlyranchdressing, it hasn't been fixed in 2.1.3 for me..

**Comment by ceyhunnabiyev** [comment]
VSCode version 1.12.2; GNOME version 3.24.

**Comment by godlyranchdressing** [comment]
I have 1.12.2 and am running 3.24 as well. This is really strange.
![b](https://cloud.githubusercontent.com/assets/27529229/26762935/8875a2c4-4918-11e7-8f69-b7a149af3d01.png)

Does it work fine for the light version? Do any other GTK2 programs have the same problem?

**Comment by ceyhunnabiyev** [comment]
>    Does it work fine for the light version? 

No @godlyranchdressing, in light version  the same problem

> Do any other GTK2 programs have the same problem?

Yes.

**Comment by ceyhunnabiyev** [comment]
Strangely it's been fixed.
